[package]
name = "inaturalist-pro-core"
version = "0.1.0"
edition = "2024"

[dependencies]
inaturalist = "0.8"
inaturalist-fetch = { path = "../inaturalist-fetch" }
oauth2 = "4.0.0"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["sync"] }
