[package]
name = "inaturalist-biodiversity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# inaturalist = "0.1.0"
geo-types = "0.7"
inaturalist = { path = "../rust-inaturalist/crate" }
lazy_static = "1"
tokio = { version = "1", features = ["full"] }
