[workspace]
members = [
    "geo-ext",
    "inaturalist-fetch",
    "inaturalist-pro-actors",
    "inaturalist-pro-config",
    "inaturalist-pro-core",
    "inaturalist-pro-geo",
    "inaturalist-pro-ui",
    "inaturalist-pro",
]
resolver = "2"
