[package]
name = "inaturalist-biodiversity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# inaturalist = "0.1.0"
async-recursion = "1"
geo = "0.20"
geojson = { version = "0.22", features = ["geo-types"] }
governor = "0.4"
inaturalist = { path = "../rust-inaturalist/crate" }
lazy_static = "1"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
