[package]
name = "inaturalist-fetch"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-recursion = "1"
geo = "0.23"
governor = "0.4"
inaturalist = "0.2"
lazy_static = "1"
ordered-float = { version = "3", features = ["serde"] }
tracing = "0.1"
